apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
    - image: stanvasilyev/gaming_client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_event
      context: event
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_slip
      context: slip
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_bet
      context: bet
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_moderation
      context: moderation
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_resulting
      context: resulting
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_backoffice
      context: backoffice
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stanvasilyev/gaming_gamemaster
      context: gamemaster
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
    - ./infra/k8s-dev/*.yaml
deploy:
  kubectl: {}
