controller:
  replicaCount: 1
  image:
    tag: v1.15.1
    digest: sha256:594ceea76b01c592858f803f9ff4d2cb40542cae2060410b2c95f75907d659e1
  admissionWebhooks:
    enabled: true
    patch:
      image:
        tag: v1.5.2
        digest: sha256:e8825994b7a2c7497375a9b945f386506ca6a3eda80b89b74ef2db743f66a5ea
      nodeSelector:
        kubernetes.io/arch: arm64
  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      oci.oraclecloud.com/load-balancer-type: "lb"
      oci.oraclecloud.com/oci-network-security-groups: "__OCI_LB_NSG_OCID__"
      service.beta.kubernetes.io/oci-load-balancer-name: "__OCI_LB_NAME__"
      service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
      service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi
  nodeSelector:
    kubernetes.io/arch: arm64
defaultBackend:
  enabled: false
