apiVersion: v1
kind: PersistentVolume
metadata:
  name: gaming-auth-mongo-data
  labels:
    betstan.io/volume-role: mongo
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: blockvolume.csi.oraclecloud.com
    fsType: ext4
    volumeHandle: __OCI_MONGO_VOLUME_OCID__
    volumeAttributes:
      attachment-type: paravirtualized
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gaming-auth-mongo-data
  labels:
    betstan.io/volume-role: mongo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: gaming-auth-mongo-data
  resources:
    requests:
      storage: 50Gi
