apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaming-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaming-client
  template:
    metadata:
      labels:
        app: gaming-client
    spec:
      containers:
        - name: gaming-client
          image: stanvasilyev/gaming_client
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gaming-client-srv
spec:
  type: ClusterIP
  selector:
    app: gaming-client
  ports:
    - name: gaming-client
      protocol: TCP
      port: 3000
      targetPort: 3000
