apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaming-resulting-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaming-resulting
  template:
    metadata:
      labels:
        app: gaming-resulting
    spec:
      containers:
        - name: gaming-resulting
          image: stanvasilyev/gaming_resulting
          # image: us.gcr.io/gaming-node-js-course/gaming_auth
          env:
            - name: MONGO_URI
              value: "mongodb://gaming-resulting-mongo-srv:27017/gaming_resulting"
            - name: RABBITMQ_URI
              value: "amqp://gaming-rabbitmq-srv"
            - name: CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gaming-resulting-srv
spec:
  type: ClusterIP
  selector:
    app: gaming-resulting
  ports:
    - name: gaming-resulting
      protocol: TCP
      port: 3000
      targetPort: 3000
