export enum EventPhase {
  PRE_MATCH = "PRE_MATCH",
  FIRST_HALF = "FIRST_HALF",
  FIRST_HALF_STOPPAGE = "FIRST_HALF_STOPPAGE",
  HALF_TIME = "HALF_TIME",
  SECOND_HALF = "SECOND_HALF",
  SECOND_HALF_STOPPAGE = "SECOND_HALF_STOPPAGE",
  FULL_TIME = "FULL_TIME",
}
