export enum LiveMarketType {
  NEXT_YELLOW_CARD = "NEXT_YELLOW_CARD",
  NEXT_RED_CARD = "NEXT_RED_CARD",
  NEXT_CORNER = "NEXT_CORNER",
  NEXT_PENALTY = "NEXT_PENALTY",
  NEXT_THROW_IN = "NEXT_THROW_IN",
  NEXT_FREE_KICK = "NEXT_FREE_KICK",
  NEXT_GOAL_KICK = "NEXT_GOAL_KICK",
  HALF_TIME_RESULT = "HALF_TIME_RESULT",
  SECOND_HALF_SCORE = "SECOND_HALF_SCORE",
  KICKOFF_TEAM = "KICKOFF_TEAM",
  FIRST_MINUTE_GOAL = "FIRST_MINUTE_GOAL",
}
