export enum LiveMarketType {
  NEXT_YELLOW_CARD = "NEXT_YELLOW_CARD",
  NEXT_RED_CARD = "NEXT_RED_CARD",
  NEXT_CORNER = "NEXT_CORNER",
  NEXT_PENALTY = "NEXT_PENALTY",
  HALF_TIME_RESULT = "HALF_TIME_RESULT",
  KICKOFF_TEAM = "KICKOFF_TEAM",
  FIRST_MINUTE_GOAL = "FIRST_MINUTE_GOAL",
}
