export enum LiveSettlementReason {
  INCIDENT = "INCIDENT",
  HALF_TIME = "HALF_TIME",
  SECOND_HALF_SCORE = "SECOND_HALF_SCORE",
  FULL_TIME_NONE = "FULL_TIME_NONE",
  MANUAL_VOID = "MANUAL_VOID",
  ACCUMULATOR_SETTLED = "ACCUMULATOR_SETTLED",
  KICK_OFF = "KICK_OFF",
  FIRST_MINUTE_GOAL = "FIRST_MINUTE_GOAL",
}
