export enum ModerationDeclineReason {
  MIXED_BET_KINDS = "MIXED_BET_KINDS",
  EVENT_STARTED = "EVENT_STARTED",
  EVENT_NOT_LIVE = "EVENT_NOT_LIVE",
  MARKET_SUSPENDED = "MARKET_SUSPENDED",
  MARKET_CLOSED = "MARKET_CLOSED",
  STALE_QUOTE = "STALE_QUOTE",
  INVALID_SELECTION = "INVALID_SELECTION",
  EVENT_RESULTED = "EVENT_RESULTED",
}
