export enum ResultingStatus {
  ROW_WIN = "ROW_WIN",
  ROW_LOSS = "ROW_LOSS",
  ROW_NO_RESULT = "ROW_NO_RESULT",
  BET_WIN = "BET_WIN",
  BET_LOSS = "BET_LOSS",
  BET_PENDING = "BET_PENDING",
  BET_APPROVED = "BET_APPROVED",
  BET_DECLINED = "BET_DECLINED",
  ROW_VOID = "ROW_VOID",
  BET_VOID = "BET_VOID",
}
