- op: remove
  path: /spec/volumeClaimTemplates
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: gaming-auth-mongo-data
      persistentVolumeClaim:
        claimName: gaming-auth-mongo-data
