name: tests-moderation

on:
  pull_request:
    paths:
      - "moderation/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: cd moderation && npm install && npm run test:ci
