name: tests-gamemaster

on:
  pull_request:
    paths:
      - "gamemaster/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd gamemaster && npm install && npm run test:ci
