name: tests-auth

on:
  pull_request:
    paths:
      - "auth/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - run: cd auth && npm install && npm run test:ci
