name: tests-resulting

on:
  pull_request:
    paths:
      - "resulting/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd resulting && npm install && npm run test:ci
